export const SET_GAMES = 'SET_GAMES'
export const ADD_GAME = 'ADD_GAME'
export const SET_GAME = 'SET_GAME'
export const CHANGE_TIMER = 'CHANGE_TIMER'
export const HIDDEN_GAME = 'HIDDEN_GAME'
export const SET_TEXTS = 'SET_TEXTS'
export const UPDATE_TIMER = 'UPDATE_TIMER'